# Generated by Django 4.1.2 on 2022-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_type_task_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='statuses', to='webapp.status', verbose_name='Status'),
        ),
    ]
