# Generated by Django 4.1.2 on 2022-10-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_status_task_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='statuses',
            field=models.ManyToManyField(related_name='statuses', to='webapp.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(related_name='types', to='webapp.type', verbose_name='Type'),
        ),
    ]
