# Generated by Django 4.1.2 on 2022-10-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_task_statuses_alter_task_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Date started')),
                ('end_date', models.DateTimeField(auto_now=True, verbose_name='Date ended')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.task')),
            ],
        ),
    ]
